# Kubernetes cluster configuration
# {{ .Release.Name }}
{{- $orgPrefix := .Values.orgPrefix -}}
{{- $environment := .Values.environment -}}
{{- $groups := .Values.groups }}
{{- $users := .Values.users }}
{{- $aksSystem := .Values.aksSystem }}
{{- $kubeAdvisor := .Values.kubeAdvisor }}

{{ if $aksSystem.enabled }}

#
# Configure aks-system namespace
#

---
# Namespace: aks-system
apiVersion: v1
kind: Namespace
metadata:
  name: aks-system

{{ end }}

#
# Configure kube-advisor RBAC requirements
#

{{ if $kubeAdvisor.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-advisor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-advisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kube-advisor
  namespace: default

{{ end }}

#
# Define roles
#

---
# RBAC role definitions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}:reader"
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch"]

---
# RBAC role definitions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}:operator"
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["*"]

#
# Configure environments
#

{{ range $environment -}}
---
# Namespace: {{ . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
{{ if $groups.reader }}
---
# Group role assignment: {{ . }}/{{ $orgPrefix }}:reader
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}-readers"
  namespace: {{ . }}
roleRef:
  kind: Role
  name: "{{ $orgPrefix }}:reader"
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $groups.reader -}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ . | quote }}
{{ end }}
{{- end }}
{{ if $groups.operator }}
---
# Group role assignment: {{ . }}/{{ $orgPrefix }}:operator
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}-operators"
  namespace: {{ . }}
roleRef:
  kind: Role
  name: "{{ $orgPrefix }}:operator"
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $groups.operator -}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ . | quote }}
{{ end }}
{{- end }}

{{ if $users.reader }}
---
# User role assignment: {{ . }}/{{ $orgPrefix }}:reader
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}-readers-users"
  namespace: {{ . }}
roleRef:
  kind: Role
  name: "{{ $orgPrefix }}:reader"
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $users.reader -}}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . | quote }}
{{ end }}
{{- end }}
{{ if $users.operator }}
---
# User role assignment: {{ . }}/{{ $orgPrefix }}:operator
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}-operators-users"
  namespace: {{ . }}
roleRef:
  kind: Role
  name: "{{ $orgPrefix }}:operator"
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $users.operator -}}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . | quote }}
{{ end }}
{{- end }}

{{ end }}

{{ if $users.admin }}
---
# User role assignment: {{ . }}/{{ $orgPrefix }}:admin
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $orgPrefix }}-admins"
roleRef:
  kind: ClusterRole
  name: "cluster-admin"
  apiGroup: rbac.authorization.k8s.io
subjects:
{{ range $users.admin -}}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . | quote }}
{{ end }}
{{- end }}
